# Definición de todos los contenedores (servicios) que necesita tu aplicación.
services:

    # 1. Servicio del Servidor Web (Nginx)
    # Recibe las peticiones del exterior y las envía a PHP-FPM.
    nginx:
        image: nginx:alpine
        container_name: egresados-nginx
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mi-red-egresados
            - web-proxy # <--- AÑADIMOS la red del proxy
        depends_on:
            - php
        labels: # <--- INSTRUCCIONES PARA TRAEFIK
            - "traefik.enable=true"
            - "traefik.http.routers.egresados.rule=Host(`egresados.test`)"
            - "traefik.http.services.egresados.loadbalancer.server.port=80"
            - "traefik.http.routers.egresados.entrypoints=web"
            - "traefik.docker.network=web-proxy"

    # 2. Servicio de PHP
    # Ejecuta el intérprete de PHP y tu aplicación Laravel.
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: egresados-php # Nombre único
        restart: unless-stopped
        user: "www-data" # <--- AÑADE ESTA LÍNEA
        volumes:
            - ./:/var/www/html
            - ~/.ssh:/var/www/.ssh:ro
        networks:
            - mi-red-egresados

    db:
        image: mysql:8.0
        container_name: egresados-db # Nombre único
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: egresados_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
                - db_data:/var/lib/mysql
        # AÑADIMOS ESTA LÍNEA 'command'
        command: '--default-authentication-plugin=mysql_native_password'
        # El puerto de la DB puede seguir expuesto si necesitas acceso directo
        ports:
            - "3307:3306"
        networks:
            - mi-red-egresados

networks:
    mi-red-egresados:
        driver: bridge
    web-proxy: # Esta sección es crucial
        external: true
# Definición de los volúmenes nombrados para persistencia de datos.
volumes:
    db_data: # El nombre que usamos arriba para el volumen de la base de datos.
